"""Build a comprehensive Vietnamese spell-correction training corpus (v2).

Versus ``prep_data.py`` (the v1 corpus), v2 adds:

  1. **Multi-register source mix.** Beyond Wiki + news, pulls in a
     legal-register slice (``train_legal_nfc.jsonl``, generated by
     ``training/diacritic/prep_data_legal.py``). Spell correction is
     used heavily in legal/business documents; v1 under-represented
     this register.
  2. **Comprehensive noise.** Round-robin over six noise presets
     (``light_noise``, ``telex_typo_noise``, ``telex_grammar_noise``,
     ``mobile_noise``, ``ocr_realistic_noise``, ``heavy_noise``)
     instead of three. Captures Telex keystroke artefacts, mobile
     fat-finger + teen-code, and segmentation-perturbed OCR — all
     real failure modes the v1 corpus barely touched.
  3. **Per-source quotas with explicit caps.** No single register
     dominates. Default quotas: 50 % Wiki+news mix (existing v1
     base), 25 % legal, 25 % oversampled hard noise on the same mix.

Output:
    training/spell_correction/data/train_v2.jsonl    (large)
    training/spell_correction/data/val_v2.jsonl      (5 K held-out)
    training/spell_correction/data/stats_v2.json     (corpus statistics)

Run::

    # Pre-req: build legal corpus first (~30 min stream from HF)
    python training/diacritic/prep_data_legal.py --max-pairs 100_000

    # Then build v2 spell-correction corpus
    python training/spell_correction/prep_data_v2.py
    python training/spell_correction/prep_data_v2.py --max-pairs 700_000

Eval-leak guards: same as v1 (drop any clean sentence appearing in
``nrl-ai/vn-spell-correction-eval`` or any of the four diacritic eval
slices).
"""

from __future__ import annotations

import argparse
import json
import sys
import unicodedata
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "src"))
from nom.text.noise import (  # noqa: E402
    NoiseConfig,
    NoiseGenerator,
    comprehensive_noise,
    heavy_noise,
    light_noise,
    mobile_noise,
    ocr_realistic_noise,
    telex_grammar_noise,
    telex_typo_noise,
)

# Reuse the v1 eval-leak guard.
sys.path.insert(0, str(REPO / "training" / "spell_correction"))
from prep_data import _eval_leak_guards  # noqa: E402

OUT_DIR = REPO / "training" / "spell_correction" / "data"

# Round-robin pool. Each preset is sampled equally across the corpus.
# Indexed by the (line_idx + variant) tuple so adjacent lines see
# different presets — gives the model balanced exposure.
_NOISE_PRESETS: tuple[tuple[str, NoiseConfig], ...] = (
    ("light_noise", light_noise()),
    ("telex_typo_noise", telex_typo_noise()),
    ("telex_grammar_noise", telex_grammar_noise()),
    ("mobile_noise", mobile_noise()),
    ("ocr_realistic_noise", ocr_realistic_noise()),
    ("heavy_noise", heavy_noise()),
)


def _pick_noise(idx: int) -> tuple[str, NoiseConfig]:
    return _NOISE_PRESETS[idx % len(_NOISE_PRESETS)]


def _stream_jsonl_targets(path: Path, blocked: set[str]) -> list[str]:
    """Read targets from a JSONL file, NFC-normalize, dedup, eval-guard."""
    targets: list[str] = []
    if not path.exists():
        return targets
    seen: set[str] = set()
    with path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            tgt = rec.get("target")
            if not tgt:
                continue
            tgt = unicodedata.normalize("NFC", tgt)
            if tgt in blocked or tgt in seen:
                continue
            seen.add(tgt)
            targets.append(tgt)
    return targets


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--source-mixed",
        type=Path,
        default=REPO / "training" / "diacritic" / "data" / "train_mixed_nfc.jsonl",
        help="The v1 Wiki+news mixed corpus (NFC-normalized).",
    )
    p.add_argument(
        "--source-legal",
        type=Path,
        default=REPO / "training" / "diacritic" / "data" / "train_legal_nfc.jsonl",
        help="The legal-register corpus from prep_data_legal.py (NFC-normalized).",
    )
    p.add_argument(
        "--max-pairs",
        type=int,
        default=600_000,
        help="Max (noisy, clean) pairs to keep total. Default 600K.",
    )
    p.add_argument(
        "--quota-mixed",
        type=float,
        default=0.65,
        help="Fraction of pairs from the Wiki+news mixed corpus.",
    )
    p.add_argument(
        "--quota-legal",
        type=float,
        default=0.25,
        help="Fraction of pairs from the legal corpus.",
    )
    p.add_argument(
        "--quota-comprehensive-only",
        type=float,
        default=0.10,
        help="Fraction of pairs that always use comprehensive_noise() instead "
        "of round-robin — dedicates capacity to the broad-mix preset.",
    )
    p.add_argument("--val-pairs", type=int, default=5_000)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument(
        "--noisy-per-clean",
        type=int,
        default=1,
        help="Augmentation factor: emit N noisy variants per clean target.",
    )
    args = p.parse_args()

    # Quota sanity check.
    total = args.quota_mixed + args.quota_legal + args.quota_comprehensive_only
    if abs(total - 1.0) > 0.01:
        print(
            f"ERROR: quotas must sum to 1.0, got {total:.3f} "
            f"(mixed={args.quota_mixed} + legal={args.quota_legal} + "
            f"comprehensive_only={args.quota_comprehensive_only})",
            file=sys.stderr,
        )
        return 2

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    blocked = _eval_leak_guards(REPO)
    print(f"eval-leak guard: {len(blocked)} sentences excluded if seen")

    if not args.source_mixed.exists():
        print(f"ERROR: missing source_mixed: {args.source_mixed}", file=sys.stderr)
        return 2
    if not args.source_legal.exists():
        print(
            f"WARNING: missing source_legal: {args.source_legal}\n"
            "         build it first via "
            "`python training/diacritic/prep_data_legal.py --max-pairs 100_000`",
            file=sys.stderr,
        )

    print(f"reading mixed targets from {args.source_mixed.name}...")
    mixed_targets = _stream_jsonl_targets(args.source_mixed, blocked)
    print(f"  {len(mixed_targets):,} unique mixed targets after eval-guard + dedup")

    print(f"reading legal targets from {args.source_legal.name}...")
    legal_targets = _stream_jsonl_targets(args.source_legal, blocked)
    print(f"  {len(legal_targets):,} unique legal targets after eval-guard + dedup")

    # Quotas (target counts).
    n_mixed = int(args.max_pairs * args.quota_mixed)
    n_legal = int(args.max_pairs * args.quota_legal)
    n_comp = args.max_pairs - n_mixed - n_legal  # remainder for comprehensive_only
    print(
        f"target quota: mixed={n_mixed:,} ({args.quota_mixed:.0%}) "
        f"legal={n_legal:,} ({args.quota_legal:.0%}) "
        f"comp_only={n_comp:,} ({args.quota_comprehensive_only:.0%})"
    )

    # Fall back BEFORE capping so the legal quota actually transfers when
    # the legal corpus is empty (the cap-by-available step would zero out
    # n_legal first and the fold-in would add nothing).
    if not legal_targets:
        print("  legal corpus empty — folding legal quota into mixed slot")
        n_mixed += n_legal
        n_legal = 0

    # Cap by available targets.
    n_mixed = min(n_mixed, len(mixed_targets) * args.noisy_per_clean)
    n_legal = min(n_legal, len(legal_targets) * args.noisy_per_clean)
    n_comp = min(n_comp, len(mixed_targets) * args.noisy_per_clean)

    train_path = OUT_DIR / "train_v2.jsonl"
    val_path = OUT_DIR / "val_v2.jsonl"
    stats_path = OUT_DIR / "stats_v2.json"

    n_train = n_val = 0
    n_skipped_no_change = 0
    preset_counts: dict[str, int] = {name: 0 for name, _ in _NOISE_PRESETS}
    preset_counts["comprehensive_noise"] = 0

    def _emit(targets: list[str], budget: int, slot_name: str, force_comprehensive: bool) -> None:
        nonlocal n_train, n_val, n_skipped_no_change
        if not targets:
            return
        idx = 0
        emitted = 0
        target_count = len(targets)
        while emitted < budget:
            target = targets[idx % target_count]
            for variant in range(args.noisy_per_clean):
                if emitted >= budget:
                    break
                seed = args.seed * 31 + idx * 7 + variant
                if force_comprehensive:
                    cfg = comprehensive_noise()
                    preset_name = "comprehensive_noise"
                else:
                    preset_name, cfg = _pick_noise(idx + variant)
                gen = NoiseGenerator(cfg, seed=seed)
                noisy = gen.noisify(target)
                if noisy == target:
                    n_skipped_no_change += 1
                    continue
                pair = {"input": noisy, "target": target}
                if n_val < args.val_pairs:
                    f_val.write(json.dumps(pair, ensure_ascii=False) + "\n")
                    n_val += 1
                else:
                    f_train.write(json.dumps(pair, ensure_ascii=False) + "\n")
                    n_train += 1
                preset_counts[preset_name] += 1
                emitted += 1
            idx += 1
            if idx > target_count * (args.noisy_per_clean + 2):
                # Defensive break: can't reach the budget even with full
                # iteration — something's fundamentally short.
                print(
                    f"  WARN: {slot_name} ran out of targets at {emitted:,}/{budget:,}",
                    file=sys.stderr,
                )
                break
        print(f"  emitted {emitted:,} pairs for slot={slot_name}")

    with (
        train_path.open("w", encoding="utf-8") as f_train,
        val_path.open("w", encoding="utf-8") as f_val,
    ):
        print("\nslot 1/3: mixed (Wiki+news), round-robin presets")
        _emit(mixed_targets, n_mixed, "mixed", force_comprehensive=False)

        if legal_targets:
            print("slot 2/3: legal, round-robin presets")
            _emit(legal_targets, n_legal, "legal", force_comprehensive=False)

        print("slot 3/3: comprehensive_noise on mixed")
        _emit(mixed_targets, n_comp, "comprehensive_only", force_comprehensive=True)

    stats = {
        "version": "v2",
        "sources": {
            "mixed": str(args.source_mixed.relative_to(REPO)),
            "legal": str(args.source_legal.relative_to(REPO)) if legal_targets else None,
        },
        "train_pairs": n_train,
        "val_pairs": n_val,
        "quotas": {
            "mixed": args.quota_mixed,
            "legal": args.quota_legal,
            "comprehensive_only": args.quota_comprehensive_only,
        },
        "preset_counts": preset_counts,
        "skipped_no_change": n_skipped_no_change,
        "noisy_per_clean": args.noisy_per_clean,
        "seed": args.seed,
    }
    stats_path.write_text(json.dumps(stats, indent=2, ensure_ascii=False) + "\n")
    print()
    print(f"wrote: {train_path} ({n_train:,} pairs)")
    print(f"wrote: {val_path}   ({n_val:,} pairs)")
    print(f"wrote: {stats_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
