"""Curated Vietnamese compound-word dictionary for nom.text.segment.

Hand-curated by Neural Research Lab. ~300 entries across business, official,
geographic, and conversational registers. Lowercase keys; tokenization is
case-insensitive but output preserves original casing.

Adding entries:
- Confirm the compound is unambiguous (one canonical form).
- Add it to the appropriate section comment for organization.
- Add a test in tests/test_segment.py exercising the new entry.

This file is data only — no imports, no executable logic. Auditable.
"""

from __future__ import annotations

# Compound words. Stored as a frozenset for O(1) lookup. Each entry is the
# space-separated form (lowercase) — tokenizer normalizes case before lookup.
COMPOUNDS: frozenset[str] = frozenset(
    {
        # === Business / contracts ===
        "hợp đồng",
        "công ty",
        "cổ phần",
        "trách nhiệm hữu hạn",
        "doanh nghiệp",
        "khách hàng",
        "nhà cung cấp",
        "ngày ký",
        "ngày lập",
        "ngày ban hành",
        "ngày có hiệu lực",
        "thời hạn",
        "giá trị hợp đồng",
        "tổng giá trị",
        "thanh toán",
        "chuyển khoản",
        "tiền mặt",
        "phương thức thanh toán",
        "điều khoản",
        "phạt vi phạm",
        "vi phạm hợp đồng",
        "tranh chấp",
        "thương lượng",
        "hoà giải",
        "trọng tài",
        "toà án",
        "pháp luật",
        "bồi thường",
        "đền bù",
        "đối tác",
        "các bên",
        "bên a",
        "bên b",
        "đại diện",
        "người đại diện",
        "chữ ký",
        "đóng dấu",
        "có hiệu lực",
        "hết hạn",
        "gia hạn",
        "thanh lý",
        "biên bản",
        "phụ lục",
        # === Government / official documents ===
        "công văn",
        "quyết định",
        "thông tư",
        "nghị định",
        "luật pháp",
        "văn bản",
        "đơn vị",
        "phòng ban",
        "uỷ ban",
        "uỷ ban nhân dân",
        "hội đồng",
        "ban giám đốc",
        "ban lãnh đạo",
        "tổng giám đốc",
        "phó giám đốc",
        "giám đốc điều hành",
        "trưởng phòng",
        "phó phòng",
        "chuyên viên",
        "nhân viên",
        "cán bộ",
        "công chức",
        "viên chức",
        "lao động",
        "tổ chức",
        "cơ quan",
        "bộ phận",
        "đơn xin",
        "đơn từ",
        "biên nhận",
        "hoá đơn",
        "biên lai",
        "chứng từ",
        "giấy tờ",
        "tài liệu",
        # === Geography / proper nouns ===
        "việt nam",
        "hà nội",
        "thành phố",
        "thành phố hồ chí minh",
        "hồ chí minh",
        "đà nẵng",
        "hải phòng",
        "cần thơ",
        "huế",
        "nha trang",
        "đà lạt",
        "vũng tàu",
        "phú quốc",
        "tỉnh thành",
        "miền bắc",
        "miền trung",
        "miền nam",
        "khu vực",
        "đông nam á",
        "châu á",
        "quốc gia",
        "đại học",
        "đại học quốc gia",
        "trường học",
        # === Time / numbers ===
        "ngày hôm nay",
        "ngày mai",
        "hôm qua",
        "tuần này",
        "tuần sau",
        "tháng này",
        "tháng sau",
        "năm nay",
        "năm sau",
        "buổi sáng",
        "buổi trưa",
        "buổi chiều",
        "buổi tối",
        "ban đêm",
        "đầu tháng",
        "cuối tháng",
        "đầu năm",
        "cuối năm",
        "hiện tại",
        "hiện nay",
        "trước đây",
        "sau này",
        # === Conversation / common verbs ===
        "có thể",
        "không thể",
        "phải làm",
        "muốn",
        "cần phải",
        "có lẽ",
        "có khi",
        "có nghĩa",
        "có nghĩa là",
        "tức là",
        "nói chung",
        "nói cách khác",
        "hơn nữa",
        "tuy nhiên",
        "do đó",
        "vì vậy",
        "vì thế",
        "cho nên",
        "thế nhưng",
        "thực tế",
        "thực ra",
        "rõ ràng",
        "chắc chắn",
        "có thể là",
        "không phải",
        "không có",
        "không bao giờ",
        "bao giờ",
        "bao nhiêu",
        "đôi khi",
        "thỉnh thoảng",
        "luôn luôn",
        "bình thường",
        "đặc biệt",
        # === AI / tech context (since users often process tech docs) ===
        "trí tuệ",
        "trí tuệ nhân tạo",
        "máy tính",
        "điện thoại",
        "mạng xã hội",
        "internet",
        "phần mềm",
        "phần cứng",
        "ứng dụng",
        "thiết bị",
        "mã nguồn",
        "mã nguồn mở",
        "dữ liệu",
        "thông tin",
        "công nghệ",
        "công nghệ thông tin",
        "khoa học",
        "kỹ thuật",
        "khoa học máy tính",
        # === Honorifics / address ===
        "kính gửi",
        "kính chào",
        "trân trọng",
        "thân mến",
        "chân thành",
        "cám ơn",
        "cảm ơn",
        "xin lỗi",
        "xin chào",
        "tạm biệt",
        "chúc mừng",
        "chúc sức khoẻ",
        # === Family / relations ===
        "bố mẹ",
        "anh chị",
        "anh em",
        "vợ chồng",
        "con cái",
        "ông bà",
        "gia đình",
        "người thân",
        # === Misc high-frequency ===
        "khi nào",
        "tại sao",
        "vì sao",
        "như thế",
        "như vậy",
        "thế nào",
        "ra sao",
        "nhiều khi",
        "dù sao",
        "ngoài ra",
        "ngược lại",
        "trái lại",
        "đồng thời",
        "cùng nhau",
        "với nhau",
        "lẫn nhau",
    }
)


# Vietnamese abbreviations that should NOT trigger a sentence boundary when
# followed by ``.``. Lowercase strings; matching is case-sensitive against
# the exact uppercase form below to avoid false positives like "ph." in normal
# prose. These are the upper-case canonical forms (e.g. "TP." for thành phố).
NEVER_SPLIT_AFTER: frozenset[str] = frozenset(
    {
        "TP",  # thành phố
        "ĐH",  # đại học
        "TS",  # tiến sĩ
        "ThS",  # thạc sĩ
        "GS",  # giáo sư
        "PGS",  # phó giáo sư
        "Mr",
        "Mrs",
        "Ms",
        "Dr",
        "St",
        "ÔB",  # ông bà
        "BS",  # bác sĩ
        "KS",  # kỹ sư
        "TT",  # tổng thống / thủ tướng
        "ĐT",  # điện thoại
        "ĐC",  # địa chỉ
        "vd",  # ví dụ
        "Vd",
        "VD",
        "etc",
    }
)
